export enum EActionTypes {
  LOGIN = 'LOGIN',
  RESET_STORE = 'RESET_STORE',
  ALL_SERVICES = 'ALL_SERVICES',
  SAVE_VENDORS = 'SAVE_VENDORS',
  SAVE_INSTADATA = 'SAVE_INSTADATA',
  SAVE_URI = 'SAVE_URI'
}
