export enum EActionTypes {
  LOGIN = 'LOGIN',
  RESET_STORE = 'RESET_STORE',
  ALL_SERVICES = 'ALL_SERVICES',
  SAVE_VENDORS = 'SAVE_VENDORS',
  UPDATE_VENDOR = 'UPDATE_VENDOR',
  SAVE_INSTADATA = 'SAVE_INSTADATA',
  UPDATE_INSTADATA = 'UPDATE_INSTADATA',
  SAVE_URI = 'SAVE_URI',
  HANDLE_AUTH_MODAL = 'HANDLE_AUTH_MODAL',
  LOG_OUT = 'LOG_OUT'
}
